### ISSUE TITLE
Iterating through strings with for-loops not working

### ISSUE THREAD

**Issue by Highly-Unstable-Hadron** [Venger-King/WaveGrass#12]
I am trying to use a for-loop to iterate through a string, but I'm getting this error and no output is printed.

Code (this is the entire code):
```
for c in 'something'{
    print(c)
}
```
Error:
 ```
0
1 | for c in 'something'{
         ^
TypeError: Assignment to a constant variable 'c'
```

I'm running the source code of the beta release v0.1.0.

**Comment by Venger-King** [comment]
fixed in v0.1.1-beta
